--
-- Drop Tables
--

SET foreign_key_checks = 0;
DROP TABLE if exists citizens;
SET foreign_key_checks = 1;

--
-- Create Tables
--
CREATE TABLE citizens(
  id                            INT NOT NULL AUTO_INCREMENT,
  firstname                     varchar(300) NOT NULL,
  lastname                      varchar(300) NOT NULL,
  id_number                     INT          NOT NULL,
  date_of_birth                 date         NOT NULL,
  place_of_birth                varchar(300) NOT NULL,
  nationality                   varchar(300) NOT NULL,
  id_status                     varchar(300) NOT NULL, 
  id_expiration_date            date         NOT NULL, 
  DNIe_status                   varchar(300) NOT NULL, 
  DNIe_expiration_date          varchar(300) NOT NULL, 
  E_ceriticate_status           varchar(300) NOT NULL, 
  E_ceriticate_expiration_date  varchar(300) NOT NULL,
  clave_status                  varchar(300) NOT NULL,
  clave_expiration_date         varchar(300) NOT NULL,
  university_degrees            varchar(300) NOT NULL, 
  masters_degrees               varchar(300) NOT NULL, 
  non_university_degrees        varchar(300) NOT NULL, 
  other_titles                  varchar(300) NOT NULL, 
  pic                           varchar(300) NOT NULL, 
  primary_care_doctor           varchar(300) NOT NULL,
  primary_care_centre           varchar(300) NOT NULL,
  blood_TYPE                    varchar(300) NOT NULL,
  vaccination_record            varchar(300) NOT NULL,
  current_diseases              varchar(1500) NOT NULL,
  past_diseases                 varchar(300) NOT NULL,
  licence_type                  varchar(300) NULL,
  licence_expedition_date       varchar(300) NOT NULL,
  licence_expiration_date       varchar(300) NOT NULL,
  licence_points_balance        INT          NULL,   
  PRIMARY KEY (id)
);


INSERT INTO citizens (firstname, lastname, id_number, date_of_birth, place_of_birth, nationality, id_status, id_expiration_date, DNIe_status, DNIe_expiration_date, E_ceriticate_status, E_ceriticate_expiration_date, clave_status, clave_expiration_date, university_degrees, masters_degrees, non_university_degrees, other_titles, pic, primary_care_doctor, primary_care_centre, blood_TYPE, vaccination_record, current_diseases, past_diseases, licence_type, licence_expedition_date, licence_expiration_date, licence_points_balance) 
  VALUES ('Iria', 
         'Moreno Rodriguez', 
          53969098, 
          '1998-08-07', 
          'Barcelona',
          'Spanish',
          'Valid',
          '2025-07-28',
          'Valid',
          '2025-07-28',
          'Expired',
          '2021-07-18',
          'Valid',
          '2026-08-29', 
          'Political Science and Public Administration', 
          'Government and Public Administration', 
          '', 
          'Full Stack Developement',
          'MORO 1 980807 01 1',
          'Dr. Alejandro Ruiz',
          'Las Acacias Health Centre',
          '0+',
          'Up to date, including varicella, influenza and hepatitis B vaccinations',
          'None',
          'Chickenpox at age 7, occasional flu',
          'B',
          '2018-07-11',
          '2028-07-11',
          14 ), 
          
          ('Andrea', 
          'Moreno Suay', 
          10000001, 
          '1997-10-20', 
          'Valencia',
          'Spanish',
          'Valid',
          '2026-06-26',
          'Expired',
          '2023-07-28',
          'Expired',
          '2021-07-28',
          'Valid',
          '2025-12-30',  
          'Tourism', 
          'Events Management', 
          '', 
          'Language courses',
          'MOSU 1 971020 01 1',
          'Dra. Marta Morales',
          'San Pablo Medical Centre',
          'A+',
          'Up to date, including tetanus, hepatitis A and B vaccinations',
          'None',
          'None of relevance',
          'B',
          '2017-11-11',
          '2027-11-11',
          14 ),
          
          ('Javier', 
          'García Hernandez', 
          10000002, 
          '1987-10-20', 
          'Valencia',
          'Spanish',
          'Expired',
          '2023-11-15',
          'Expired',
          '2021-07-28',
          'Valid',
          '2028-03-12',
          'Expired',
          '2021-07-15',  
          'Tourism', 
          'Events Management', 
          '', 
          'Language courses',
          'GAHE 1 871020 01 1',
          'Dr. Javier Benítez',
          'Virgen del Rocío Clinic',
          'AB+',
          'Complete and up to date, including human papilloma vaccine and malaria vaccine before a trip to Latin America',
          'After a series of tests, he is diagnosed with Crohn',
          'Occasional flu and appendicitis',
          'C',
          '2023-11-11',
          '2033-11-11',
          08 ),
          
          ('Carla', 
          'Fernandez Ramos', 
          10000003, 
          '1987-07-10', 
          'Granada',
          'Spanish',
          'Valid',
          '2028-09-21',
          'Valid',
          '2029-09-18',
          'Non subscribed',
          '',
          'Valid',
          '2025-06-28',  
          'Medicine', 
          'Cardiology', 
          '', 
          'Childs cardiology',
          'FERA 1 070131 01 1',
          'Dra. Andrea Gómez',
          'Juan XXIII Primary Care Centre',
          '0-',
          'Up to date, with all the recommended vaccinations according to their age.',
          'None',
          'Mononucleosis at 18, seasonal allergies.',
          'None',
          '',
          '',
          0 ),
          
          ('Ingrid', 
          'Segovia López', 
          10000004, 
          '1998-11-26', 
          'Hostalric',
          'Spanish',
          'Expired',
          '2023-11-13',
          'Valid',
          '2026-06-26',
          'Valid',
          '2025-08-31',
          'Expired',
          '2023-10-21',  
          'Political Science', 
          'Public Administration', 
          '', 
          'Theatre studies',
          'SELO 1 981126 01 1',
          'Dr. Juan Carlos Sánchez',
          'El Bosque Medical Clinic',
          'A-',
          'Complete, including measles, rubella and varicella vaccination.',
          'Ingrid presents with symptoms of an overactive thyroid, including unexplained weight loss, excessive sweating and fatigue. After laboratory tests, she is diagnosed with Graves disease and is recommended for treatment with antithyroid medication and possibly radioactive iodine therapy.',
          'Asthma since childhood, appendicitis at the age of 24',
          'B',
          '2020-11-19',
          '2030-11-19',
          8),
          
          ('Oriol', 
          'Roca Gual', 
          10000005, 
          '1936-07-18', 
          'Sant Joan Despí',
          'Spanish',
          'Valid',
          '2030-11-18',
          'Expired',
          '2020-07-24',
          'Valid',
          '2030-07-13',
          'Expired',
          '2023-09-28',  
          'Public Relationships', 
          'Mass Media and Political Parties Propaganda', 
          '', 
          'Speech course', 
          'ROGU 1 360718 01 1',
          'Dra. Laura Torres',
          'Los Alamos Health Centre',
          'B+',
          'Updated, including vaccinations against tetanus and hepatitis A and B.',
          'Oriol has noticed memory problems and difficulty concentrating. After a neurological evaluation, he is diagnosed with early stage Alzheimer disease and a therapeutic approach including medication and occupational therapy is suggested.',
          'Pneumonia at 35 years of age, arterial hypertension.',
          'B',
          '2015-07-08',
          '2020-07-08',
          0),
          
          ('Esther', 
          'Rodriguez Montes', 
          10000006, 
          '1971-05-13', 
          'Cornella',
          'Spanish',
          'Valid',
          '2027-07-28',
          'Expired',
          '2021-11-21',
          'Expired',
          '2020-11-22',
          'Valid',
          '2031-11-21',  
          'Design', 
          'Retail Management', 
          '', 
          'Accountancy',
          'ROMO 1 710513 01 1',
          'Dr. Pedro Ramos',
          'La Paz Clinic',
          'AB-',
          'Complete and up to date, including seasonal flu vaccination.',
          'None',
          'Seasonal allergies, ankle fracture at the age of 20.',
          'None',
          '',
          '',
          0),
          
          ('Marc', 
          'Minoves Grau', 
          10000007, 
          '2001-10-01', 
          'Berga',
          'Spanish',
          'Expired',
          '2023-09-05',
          'Expired',
          '2022-04-22',
          'Non - subscribed',
          '',
          'Valid',
          '2028-12-12',  
          'Architecture', 
          'Urban Planning', 
          '', 
          'Language courses',
          'MIGR 1 011001 01 1',
          'Dra. Carmen López',
          'Ciudad Jardín Medical Centre',
          '0-',
          'Up to date with all recommended vaccinations for their age, including malaria vaccination prior to travel to Africa.',
          'None',
          'None of relevance',
          'None',
          '',
          '',
          0),
          
          ('Andres', 
          'Ramos Cortés', 
          10000008, 
          '1950-04-20', 
          'Navarra',
          'Spanish',
          'Valid',
          '2031-07-11',
          'Expired',
          '2022-03-29',
          'Valid',
          '2032-05-17',
          'Valid',
          '2026-05-24',  
          'Industrial Engineering', 
          'Big Data', 
          '', 
          'Language courses',
          'RACO 1 500420 01 1',
          'Dr. Manuel Castro',
          'San Isidro Primary Care Centre',
          'A+',
          'Complete, including meningitis vaccination.',
          'Marta has a history of uncontrolled type 2 diabetes and high blood pressure. Recently, she has experienced vision problems and numbness in her extremities. After an ophthalmological and neurological evaluation, she is diagnosed with diabetic retinopathy and peripheral neuropathy, and a multidisciplinary treatment plan is initiated.',
          'Food allergies, appendicitis at age 20.',
          'B',
          '2023-03-11',
          '2028-03-11',
          14),
          
          ('Raquel', 
          'Castellano Lorenzo', 
          10000009, 
          '1967-12-03', 
          'Cáceres',
          'Spanish',
          'Expired',
          '2023-10-29',
          'Valid',
          '2027-07-19',
          'Valid',
          '2029-09-29',
          'Expired',
          '2023-05-22',  
          'Physics', 
          'Astrophysics', 
          '', 
          'Language courses',
          'CALO 1 671203 01 1',
          'Dra. María Rodríguez',
          'El Prado Medical Clinic',
          'B-',
          'Updated, including seasonal flu vaccination.',
          'Raquel suffers from frequent migraines accompanied by nausea and sensitivity to light. After a neurological examination and additional tests, you are diagnosed with chronic migraine and prescribed pain relief medication and lifestyle changes.',
          'Chronic bronchitis, appendicitis at the age of 25.',
          'B',
          '2022-02-10',
          '2027-02-10',
          14);


